#pragma once

#include <stdbool.h>
#include <stdint.h>


typedef enum {
    LED_NONE             = 0,

    LED_USB_G            = (1<<0),
    LED_USB_Y            = (1<<1),

    LED_BAT_BOTTOM_R     = (1<<2),
    LED_BAT_BOTTOM_Y1    = (1<<3),
    LED_BAT_BOTTOM_Y2    = (1<<4),
    LED_BAT_BOTTOM_G1    = (1<<5),
    LED_BAT_BOTTOM_G2    = (1<<6),

    LED_BAT_TOP_R        = (1<<7),
    LED_BAT_TOP_Y1       = (1<<8),
    LED_BAT_TOP_Y2       = (1<<9),
    LED_BAT_TOP_G1       = (1<<10),
    LED_BAT_TOP_G2       = (1<<11),

    LED_SEG_DOT_TOP      = (1<<12),
    LED_SEG_DOT_BOTTOM   = (1<<13),
    LED_SEG_TOP          = (1<<14),
    LED_SEG_TOP_LEFT     = (1<<15),
    LED_SEG_TOP_RIGHT    = (1<<16),
    LED_SEG_MIDDLE       = (1<<17),
    LED_SEG_BOTTOM       = (1<<18),
    LED_SEG_BOTTOM_LEFT  = (1<<19),
    LED_SEG_BOTTOM_RIGHT = (1<<20),

    LED_SEG_0 = LED_SEG_TOP | LED_SEG_TOP_LEFT | LED_SEG_TOP_RIGHT | LED_SEG_BOTTOM | LED_SEG_BOTTOM_LEFT | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_1 = LED_SEG_TOP_RIGHT | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_2 = LED_SEG_TOP | LED_SEG_TOP_RIGHT | LED_SEG_MIDDLE | LED_SEG_BOTTOM_LEFT | LED_SEG_BOTTOM,
    LED_SEG_3 = LED_SEG_TOP | LED_SEG_TOP_RIGHT | LED_SEG_MIDDLE | LED_SEG_BOTTOM | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_4 = LED_SEG_TOP_LEFT | LED_SEG_TOP_RIGHT | LED_SEG_MIDDLE | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_5 = LED_SEG_TOP | LED_SEG_TOP_LEFT | LED_SEG_MIDDLE | LED_SEG_BOTTOM | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_6 = LED_SEG_TOP | LED_SEG_TOP_LEFT | LED_SEG_MIDDLE | LED_SEG_BOTTOM | LED_SEG_BOTTOM_LEFT | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_7 = LED_SEG_TOP | LED_SEG_TOP_RIGHT | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_8 = LED_SEG_TOP | LED_SEG_TOP_LEFT | LED_SEG_TOP_RIGHT | LED_SEG_MIDDLE | LED_SEG_BOTTOM | LED_SEG_BOTTOM_LEFT | LED_SEG_BOTTOM_RIGHT,
    LED_SEG_9 = LED_SEG_TOP | LED_SEG_TOP_LEFT | LED_SEG_TOP_RIGHT | LED_SEG_MIDDLE | LED_SEG_BOTTOM | LED_SEG_BOTTOM_RIGHT,
} led_t;

void leds_init();
bool leds_set_all(uint32_t states);
